services:
  postgres:
    image: postgres:16
    container_name: oss_postgres
    restart: always
    environment:
      POSTGRES_USER: ossuser
      POSTGRES_PASSWORD: osspass123
      POSTGRES_DB: oss_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ossuser -d oss_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: